apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: skaffold-demo
build:
  artifacts:
  - image: roukou/skaffold-demo
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-app.yml
profiles:
- name: skaffold-demo
  activation:
    - kubeContext: docker-desktop
      command: demo
